add page "dashboard" and add graph
ArtsiomDziominski/todolist pull request #5
Opened 2022-08-07 15:32 UTC by ArtsiomDziominski

add page "dashboard" and add grap
![Снимок экрана 2022-08-07 193045](https://user-images.githubusercontent.com/86887225/183298656-e05061b2-c72e-4819-be3e-ee773b1c034a.png)

2022-08-08 16:26 UTC, NikaTikhonovets requested changes

2022-08-08 16:26 UTC, NikaTsikhanavets commented on src/app/components/full-version/full-version.component.ts
> +    console.log(this.allTasks)
убрать

2022-08-08 16:26 UTC, NikaTsikhanavets commented on src/app/components/graph/chart-js/chart-js.component.ts
> +          data: [this.statistics[0].frequency, this.statistics[1].frequency, this.statistics[2].frequency],
вынести в map

2022-08-08 16:26 UTC, NikaTsikhanavets commented on src/app/components/graph/chart-js/chart-js.component.ts
> +          label: '# of Votes',
...CHART_JS_CONFIG,

2022-08-08 16:26 UTC, NikaTsikhanavets commented on src/app/components/graph/d3/d3.component.ts
> +  private x: any;
any!!!

2022-08-08 16:26 UTC, NikaTsikhanavets commented on src/app/components/graph/d3/d3.component.ts
> +    this.x = d3Scale
() => number

2022-08-08 16:26 UTC, NikaTsikhanavets commented on src/app/components/graph/d3/d3.component.ts
> +    this.x = d3Scale
{[key: string]: any}

2022-08-08 16:26 UTC, NikaTsikhanavets commented on src/app/components/graph/d3/d3.component.ts
> +    this.x.domain(this.statistics.map(d => d.letter));
добавь константу

2022-08-08 16:26 UTC, NikaTsikhanavets commented on src/app/components/graph/d3/d3.component.ts
> +    this.y.domain([0, d3Array.max(this.statistics, d => d.frequency)]);
добавь константу

2022-08-08 16:26 UTC, NikaTsikhanavets commented on src/app/components/pages/dashboard/dashboard.component.html
> +        <mat-option value="d3-bar" (click)="isToggleGraph=!isToggleGraph">d3 bar</mat-option>
вынести в ts

2022-08-08 16:26 UTC, NikaTsikhanavets commented on src/app/components/pages/dashboard/dashboard.component.html
> +    <app-d3 [statistics]="statistics"></app-d3>
*ngIf="isToggleGraph; else templateName"

2022-08-08 16:26 UTC, NikaTsikhanavets commented on src/app/components/pages/dashboard/dashboard.component.html
> +  <ng-template [ngIf]="!isToggleGraph">
#templateName

2022-08-08 16:26 UTC, NikaTsikhanavets commented on src/app/components/pages/dashboard/dashboard.component.ts
> +  public isToggleGraph: boolean = true;
переименовать

2022-08-08 16:26 UTC, NikaTsikhanavets commented on src/app/components/pages/dashboard/dashboard.component.ts
> +      if (count.status === 'todo') {
enum

2022-08-08 16:26 UTC, NikaTsikhanavets commented on src/app/components/pages/dashboard/dashboard.component.ts
> +      if (count.status === 'todo') {
switch case

2022-08-08 16:26 UTC, NikaTsikhanavets commented on src/app/components/pages/dashboard/dashboard.component.ts
> +    this.allTasks.forEach((count) => {
this.allTasks.filter + .length

2022-08-08 16:26 UTC, NikaTsikhanavets commented on src/app/components/pages/dashboard/dashboard.component.ts
> +    let toDo: string = 'To Do';
const

2022-08-08 16:27 UTC, ArtsiomDziominski commented on src/app/components/full-version/full-version.component.ts
> +    console.log(this.allTasks)
удалю

2022-08-08 16:27 UTC, ArtsiomDziominski commented on src/app/components/graph/chart-js/chart-js.component.ts
> +  constructor() { }
удалю

2022-08-08 16:27 UTC, ArtsiomDziominski commented on src/app/components/graph/chart-js/chart-js.component.ts
> +  ngOnInit(): void {
ага

2022-08-13 13:00 UTC, GeorgyGradinar commented on src/app/components/graph/d3/d3.component.ts
> +  private initSvg() {
void

2022-08-13 13:00 UTC, GeorgyGradinar commented on src/app/components/graph/d3/d3.component.ts
> +  private initAxis() {
void

2022-08-13 13:00 UTC, GeorgyGradinar commented on src/app/components/graph/d3/d3.component.ts
> +  private drawAxis() {
void

2022-08-13 13:00 UTC, GeorgyGradinar commented on src/app/components/graph/d3/d3.component.ts
> +  private drawBars() {
void

2022-08-13 13:00 UTC, GeorgyGradinar commented on src/app/components/graph/chart-js-line/chart-js-line.component.ts
> +    let width:any = document.getElementsByClassName('chart');
Есть подозрение, что Нике не понравиться getElement в ангуляре

2022-08-13 13:00 UTC, GeorgyGradinar commented on src/app/components/graph/chart-js-pie/chart-js-pie.component.ts
> +  onResize() {
Public, void

2022-08-13 13:00 UTC, GeorgyGradinar commented on src/app/components/graph/chart-js/chart-js.component.ts
> +  onResize() {
public, void

2022-08-13 13:00 UTC, GeorgyGradinar commented on src/app/components/graph/d3-line/d3-line.component.ts
> +  private initAxis() {
void

2022-08-13 13:00 UTC, GeorgyGradinar commented on src/app/components/graph/d3-line/d3-line.component.ts
> +  private drawAxis() {
void

2022-08-13 13:00 UTC, GeorgyGradinar commented on src/app/components/graph/d3-line/d3-line.component.ts
> +  private drawLine() {
void

2022-08-13 13:00 UTC, GeorgyGradinar commented on src/app/components/graph/d3-line/d3-line.component.ts
> +  public drawArea() {
void

2022-08-13 13:00 UTC, GeorgyGradinar commented on src/app/components/graph/d3-line/d3-line.component.ts
> +  public circle() {
void

2022-08-13 13:00 UTC, GeorgyGradinar commented on src/app/components/graph/d3-line/d3-line.component.ts
> +  public info() {
void

2022-08-16 13:46 UTC, NikaTikhonovets requested changes

2022-08-16 13:46 UTC, NikaTikhonovets commented on src/app/components/const/get-gradient-graph.ts
> +export function getGradient(ctx:any, chartArea:any) {
для этого лучше использовать сервисы

2022-08-16 13:46 UTC, NikaTikhonovets commented on src/app/components/const/get-gradient-graph.ts
> +let width:number, height:number, gradient:any;
а почему они вне функции?

2022-08-16 13:46 UTC, NikaTikhonovets commented on src/app/components/graph/chart-js-line/chart-js-line.component.ts
> +    let width:any = document.getElementsByClassName('chart');
Жора, все верно, для конкретно такого случая лучше исспользовать ангуляровский механизм получения элемента из html - ViewChild https://angular.io/api/core/ViewChild

2022-08-16 13:46 UTC, NikaTikhonovets commented on src/app/components/graph/chart-js-line/chart-js-line.component.ts
> +    let width:any = document.getElementsByClassName('chart');
плюс здесь нет типа
да и еще странное название width, хотя ты ожидаешь получить элемент

2022-08-16 13:46 UTC, NikaTikhonovets commented on src/app/components/graph/chart-js-pie/chart-js-pie.component.ts
> +    let width:any = document.getElementsByClassName( 'chart' );
сюда применимы все те же комментарии, что и к предыдущему графику

2022-08-21 07:23 UTC, merged